@startuml

package "IN OUR CONTROL" {
database Database
[Velo Service (WireMock)] as velo #lightgreen
package "Spring Boot" {
[Spring Boot Service] <--> Database
[Spring Boot Service] <--> velo: Sync every 30 seconds

}
}

HTTP --> [Spring Boot Service]: REST API

@enduml
