@startuml


cloud {
 [Velo Service] as velo
}

package "IN OUR CONTROL" {

package "Spring Boot" {
database "In Memory Database" as Database
[Spring Boot Service] as spring
spring -> Database: Liquibase: Creates tables on startup
spring <--> Database
spring <--> velo: Sync every 30 seconds

}
}

HTTP --> spring: REST API

@enduml
